event:
    resource: "@EventBundle/Resources/config/routing.yml"
    prefix:   /
#user_controller:
#    resource: "@UserBundle/Controller"
#    prefix:   /
#    type:      annotation

baseball_controller:
    resource: "@BaseballBundle/Controller"
    prefix:   /
    type:      annotation

#carpool_controller:
#    resource: "@CarpoolBundle/Resources/config/routing.yml"
#    prefix:   /

carpool_controller:
    resource: "@CarpoolBundle/Controller"
    prefix:   /
    type:      annotation

streak_controller:
    resource: "@StreakBundle/Controller"
    prefix:   /
    type:      annotation

angular_controller:
    resource: "@AngularBundle/Controller"
    prefix:   /
    type:      annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
